import { MigrationInterface, QueryRunner } from "typeorm";

export class AddSupplierChatSupport1786438822794 implements MigrationInterface {
    name = 'AddSupplierChatSupport1786438822794'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_users_beta_photo_file"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_order_items_file_metadata"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_orders_file_metadata"`);
        await queryRunner.query(`ALTER TABLE "supplier_capabilities" DROP CONSTRAINT "FK_supplier_capabilities_supplier_id"`);
        await queryRunner.query(`ALTER TABLE "supplier_verifications" DROP CONSTRAINT "FK_supplier_verifications_reviewed_by"`);
        await queryRunner.query(`ALTER TABLE "supplier_verifications" DROP CONSTRAINT "FK_supplier_verifications_supplier_id"`);
        await queryRunner.query(`ALTER TABLE "supplier_profiles" DROP CONSTRAINT "fk_supplier_profiles_logo_file"`);
        await queryRunner.query(`ALTER TABLE "supplier_profiles" DROP CONSTRAINT "FK_supplier_profiles_user_id"`);
        await queryRunner.query(`ALTER TABLE "rider_profiles" DROP CONSTRAINT "FK_rider_profiles_verification_reviewed_by"`);
        await queryRunner.query(`ALTER TABLE "delivery_assignments" DROP CONSTRAINT "FK_delivery_assignments_proof_file"`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" DROP CONSTRAINT "FK_quality_reviews_reviewer_id"`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" DROP CONSTRAINT "FK_quality_reviews_order_id"`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "fk_product_categories_parent"`);
        await queryRunner.query(`ALTER TABLE "service_addons" DROP CONSTRAINT "FK_service_addons_product_category"`);
        await queryRunner.query(`ALTER TABLE "pickup_qa_submissions" DROP CONSTRAINT "pickup_qa_submissions_actor_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pickup_qa_submissions" DROP CONSTRAINT "pickup_qa_submissions_order_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP CONSTRAINT "FK_payouts_release_authority_id"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP CONSTRAINT "FK_payouts_order_id"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP CONSTRAINT "FK_payouts_supplier_id"`);
        await queryRunner.query(`ALTER TABLE "qr_payment_receipts" DROP CONSTRAINT "qr_payment_receipts_verified_by_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "qr_payment_receipts" DROP CONSTRAINT "qr_payment_receipts_file_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "qr_payment_receipts" DROP CONSTRAINT "qr_payment_receipts_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "qr_payment_receipts" DROP CONSTRAINT "qr_payment_receipts_batch_order_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "qr_payment_receipts" DROP CONSTRAINT "qr_payment_receipts_order_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "cod_collections" DROP CONSTRAINT "FK_cod_collections_reconciled_by_user_id"`);
        await queryRunner.query(`ALTER TABLE "cod_collections" DROP CONSTRAINT "FK_cod_collections_rider_id"`);
        await queryRunner.query(`ALTER TABLE "cod_collections" DROP CONSTRAINT "FK_cod_collections_order_id"`);
        await queryRunner.query(`ALTER TABLE "artwork_mockup_renders" DROP CONSTRAINT "FK_mockup_order"`);
        await queryRunner.query(`ALTER TABLE "artwork_mockup_renders" DROP CONSTRAINT "FK_mockup_artwork_file"`);
        await queryRunner.query(`ALTER TABLE "supplier_assignments" DROP CONSTRAINT "FK_supplier_assignments_supplier_id"`);
        await queryRunner.query(`ALTER TABLE "supplier_assignments" DROP CONSTRAINT "FK_supplier_assignments_order_id"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_issues_resolved_by_user_id"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_issues_opened_by_user_id"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_issues_order_id"`);
        await queryRunner.query(`ALTER TABLE "audit_events" DROP CONSTRAINT "FK_audit_events_order_id"`);
        await queryRunner.query(`ALTER TABLE "audit_events" DROP CONSTRAINT "FK_audit_events_actor_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_beta_enrollment_rank"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_categories_parent_id"`);
        await queryRunner.query(`DROP INDEX "public"."uq_qr_payment_receipts_order_id"`);
        await queryRunner.query(`ALTER TYPE "public"."users_profile_category_enum" RENAME TO "users_profile_category_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_profile_category_enum" AS ENUM('student', 'professional', 'supplier', 'rider')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "profile_category" TYPE "public"."users_profile_category_enum" USING "profile_category"::"text"::"public"."users_profile_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_profile_category_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."orders_payment_authorization_status_enum" RENAME TO "orders_payment_authorization_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."orders_payment_authorization_status_enum" AS ENUM('none', 'authorized', 'failed', 'expired')`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "payment_authorization_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "payment_authorization_status" TYPE "public"."orders_payment_authorization_status_enum" USING "payment_authorization_status"::"text"::"public"."orders_payment_authorization_status_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "payment_authorization_status" SET DEFAULT 'none'`);
        await queryRunner.query(`DROP TYPE "public"."orders_payment_authorization_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "rider_profiles" ALTER COLUMN "verification_status" SET DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TYPE "public"."quality_reviews_decision_enum" RENAME TO "quality_reviews_decision_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."quality_reviews_decision_enum" AS ENUM('needs_correction', 'proof_approval', 'approved_for_matching', 'blocked')`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" ALTER COLUMN "decision" TYPE "public"."quality_reviews_decision_enum" USING "decision"::"text"::"public"."quality_reviews_decision_enum"`);
        await queryRunner.query(`DROP TYPE "public"."quality_reviews_decision_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."quality_reviews_risk_level_enum" RENAME TO "quality_reviews_risk_level_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."quality_reviews_risk_level_enum" AS ENUM('low', 'medium', 'high')`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" ALTER COLUMN "risk_level" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" ALTER COLUMN "risk_level" TYPE "public"."quality_reviews_risk_level_enum" USING "risk_level"::"text"::"public"."quality_reviews_risk_level_enum"`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" ALTER COLUMN "risk_level" SET DEFAULT 'low'`);
        await queryRunner.query(`DROP TYPE "public"."quality_reviews_risk_level_enum_old"`);
        await queryRunner.query(`ALTER TABLE "product_categories" ALTER COLUMN "allowed_extensions" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "pickup_qa_submissions" ALTER COLUMN "checklist_results" DROP DEFAULT`);
        await queryRunner.query(`ALTER TYPE "public"."payouts_settlement_state_enum" RENAME TO "payouts_settlement_state_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."payouts_settlement_state_enum" AS ENUM('pending', 'held', 'released', 'settled', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "settlement_state" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "settlement_state" TYPE "public"."payouts_settlement_state_enum" USING "settlement_state"::"text"::"public"."payouts_settlement_state_enum"`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "settlement_state" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."payouts_settlement_state_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."file_metadata_purpose_enum" RENAME TO "file_metadata_purpose_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."file_metadata_purpose_enum" AS ENUM('general', 'paper', 'proof_of_delivery', 'beta_testimonial', 'payment_receipt', 'legacy')`);
        await queryRunner.query(`ALTER TABLE "file_metadata" ALTER COLUMN "purpose" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "file_metadata" ALTER COLUMN "purpose" TYPE "public"."file_metadata_purpose_enum" USING "purpose"::"text"::"public"."file_metadata_purpose_enum"`);
        await queryRunner.query(`ALTER TABLE "file_metadata" ALTER COLUMN "purpose" SET DEFAULT 'general'`);
        await queryRunner.query(`DROP TYPE "public"."file_metadata_purpose_enum_old"`);
        await queryRunner.query(`ALTER TABLE "qr_payment_receipts" ADD CONSTRAINT "UQ_9edbb605ea3d25cff2b6afe9d9a" UNIQUE ("order_id")`);
        await queryRunner.query(`ALTER TYPE "public"."cod_collections_status_enum" RENAME TO "cod_collections_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."cod_collections_status_enum" AS ENUM('pending', 'collected', 'failed', 'reconciled')`);
        await queryRunner.query(`ALTER TABLE "cod_collections" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "cod_collections" ALTER COLUMN "status" TYPE "public"."cod_collections_status_enum" USING "status"::"text"::"public"."cod_collections_status_enum"`);
        await queryRunner.query(`ALTER TABLE "cod_collections" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."cod_collections_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "artwork_mockup_renders" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "artwork_mockup_renders" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "artwork_mockup_renders" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "artwork_mockup_renders" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."supplier_assignments_decision_enum" RENAME TO "supplier_assignments_decision_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."supplier_assignments_decision_enum" AS ENUM('pending', 'accepted', 'declined', 'expired', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "supplier_assignments" ALTER COLUMN "decision" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "supplier_assignments" ALTER COLUMN "decision" TYPE "public"."supplier_assignments_decision_enum" USING "decision"::"text"::"public"."supplier_assignments_decision_enum"`);
        await queryRunner.query(`ALTER TABLE "supplier_assignments" ALTER COLUMN "decision" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."supplier_assignments_decision_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."issues_status_enum" RENAME TO "issues_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."issues_status_enum" AS ENUM('open', 'under_review', 'resolved_refund', 'resolved_reprint', 'resolved_adjustment', 'rejected', 'closed')`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "status" TYPE "public"."issues_status_enum" USING "status"::"text"::"public"."issues_status_enum"`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "status" SET DEFAULT 'open'`);
        await queryRunner.query(`DROP TYPE "public"."issues_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."issues_payout_impact_enum" RENAME TO "issues_payout_impact_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."issues_payout_impact_enum" AS ENUM('none', 'hold', 'freeze', 'release')`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "payout_impact" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "payout_impact" TYPE "public"."issues_payout_impact_enum" USING "payout_impact"::"text"::"public"."issues_payout_impact_enum"`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "payout_impact" SET DEFAULT 'hold'`);
        await queryRunner.query(`DROP TYPE "public"."issues_payout_impact_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."home_feed_settings_mode_enum" RENAME TO "home_feed_settings_mode_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."home_feed_settings_mode_enum" AS ENUM('auto', 'community', 'promo')`);
        await queryRunner.query(`ALTER TABLE "home_feed_settings" ALTER COLUMN "mode" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "home_feed_settings" ALTER COLUMN "mode" TYPE "public"."home_feed_settings_mode_enum" USING "mode"::"text"::"public"."home_feed_settings_mode_enum"`);
        await queryRunner.query(`ALTER TABLE "home_feed_settings" ALTER COLUMN "mode" SET DEFAULT 'auto'`);
        await queryRunner.query(`DROP TYPE "public"."home_feed_settings_mode_enum_old"`);
        await queryRunner.query(`DROP INDEX "public"."idx_conv_status_type"`);
        await queryRunner.query(`ALTER TYPE "public"."chat_conversations_type_enum" RENAME TO "chat_conversations_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."chat_conversations_type_enum" AS ENUM('ai', 'admin', 'rider', 'supplier')`);
        await queryRunner.query(`ALTER TABLE "chat_conversations" ALTER COLUMN "type" TYPE "public"."chat_conversations_type_enum" USING "type"::"text"::"public"."chat_conversations_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."chat_conversations_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."chat_messages_sender_role_enum" RENAME TO "chat_messages_sender_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."chat_messages_sender_role_enum" AS ENUM('customer', 'admin', 'rider', 'bot', 'supplier')`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ALTER COLUMN "sender_role" TYPE "public"."chat_messages_sender_role_enum" USING "sender_role"::"text"::"public"."chat_messages_sender_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."chat_messages_sender_role_enum_old"`);
        await queryRunner.query(`CREATE INDEX "idx_conv_status_type" ON "chat_conversations" ("status", "type") `);
        await queryRunner.query(`ALTER TABLE "supplier_capabilities" ADD CONSTRAINT "FK_2a232dc1548bdf87736c71fa4b3" FOREIGN KEY ("supplier_id") REFERENCES "supplier_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_verifications" ADD CONSTRAINT "FK_f158ddce866302cc0af9bbc9022" FOREIGN KEY ("supplier_id") REFERENCES "supplier_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_verifications" ADD CONSTRAINT "FK_ac4469cd2ce4bd70f2c14ea2cbe" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_profiles" ADD CONSTRAINT "FK_d8f0b495dba71509b24110ef9ea" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rider_profiles" ADD CONSTRAINT "FK_750cddd36444ac18bb47b26de12" FOREIGN KEY ("verification_reviewed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" ADD CONSTRAINT "FK_efef9648ccb478a9f43efaa2223" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" ADD CONSTRAINT "FK_47ad026956606bbc43a0f47ab68" FOREIGN KEY ("reviewer_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "FK_5f151d414daab0290f65b517ed4" FOREIGN KEY ("parent_id") REFERENCES "product_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_addons" ADD CONSTRAINT "FK_2f041a59cfc5c4b85b2f04708d4" FOREIGN KEY ("category_id") REFERENCES "product_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pickup_qa_submissions" ADD CONSTRAINT "FK_329712563e73857f495256914d0" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pickup_qa_submissions" ADD CONSTRAINT "FK_68f312df26e22b3090e4e0ce8e2" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD CONSTRAINT "FK_3dfd4035df06755fed74ed9a667" FOREIGN KEY ("supplier_id") REFERENCES "supplier_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD CONSTRAINT "FK_bfb05759855bf6da289123ee9cd" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD CONSTRAINT "FK_b00d01b12915d8aefab8806cfee" FOREIGN KEY ("release_authority_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qr_payment_receipts" ADD CONSTRAINT "FK_9edbb605ea3d25cff2b6afe9d9a" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qr_payment_receipts" ADD CONSTRAINT "FK_e1b918f8a3242def69efa2f8ae8" FOREIGN KEY ("batch_order_id") REFERENCES "batch_orders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qr_payment_receipts" ADD CONSTRAINT "FK_5ed72366aea950d412e54fc336e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qr_payment_receipts" ADD CONSTRAINT "FK_4f1c5984edfa53b368de0ba95ca" FOREIGN KEY ("file_id") REFERENCES "file_metadata"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qr_payment_receipts" ADD CONSTRAINT "FK_0586e8f04b0d23e1829ff962bc5" FOREIGN KEY ("verified_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cod_collections" ADD CONSTRAINT "FK_0795a96c2d82de035ed1f76d505" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cod_collections" ADD CONSTRAINT "FK_a4b3b775b423b95c084e9cf67ed" FOREIGN KEY ("rider_id") REFERENCES "rider_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cod_collections" ADD CONSTRAINT "FK_6e62e27fb72e942cd7c5a71cae9" FOREIGN KEY ("reconciled_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artwork_mockup_renders" ADD CONSTRAINT "FK_1f670ee5397062b364c69a28fa0" FOREIGN KEY ("artwork_file_id") REFERENCES "file_metadata"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artwork_mockup_renders" ADD CONSTRAINT "FK_a4d6e33ccf0d0e0f835818d9cbc" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_assignments" ADD CONSTRAINT "FK_d13f8fe27a7f0f6dd6ce2dafac7" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_assignments" ADD CONSTRAINT "FK_eeef10a137fdc587c70d1cc9916" FOREIGN KEY ("supplier_id") REFERENCES "supplier_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_66d34378020b3cc628b3c71efcd" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_6d9029561eeca7c2ee2c0f89087" FOREIGN KEY ("opened_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_d77e05cdb427a1bd511b3f3f87b" FOREIGN KEY ("resolved_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_events" ADD CONSTRAINT "FK_04c7c044146c6632491a370fc04" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_events" ADD CONSTRAINT "FK_72920f1cde49d4abcf935953301" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "audit_events" DROP CONSTRAINT "FK_72920f1cde49d4abcf935953301"`);
        await queryRunner.query(`ALTER TABLE "audit_events" DROP CONSTRAINT "FK_04c7c044146c6632491a370fc04"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_d77e05cdb427a1bd511b3f3f87b"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_6d9029561eeca7c2ee2c0f89087"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_66d34378020b3cc628b3c71efcd"`);
        await queryRunner.query(`ALTER TABLE "supplier_assignments" DROP CONSTRAINT "FK_eeef10a137fdc587c70d1cc9916"`);
        await queryRunner.query(`ALTER TABLE "supplier_assignments" DROP CONSTRAINT "FK_d13f8fe27a7f0f6dd6ce2dafac7"`);
        await queryRunner.query(`ALTER TABLE "artwork_mockup_renders" DROP CONSTRAINT "FK_a4d6e33ccf0d0e0f835818d9cbc"`);
        await queryRunner.query(`ALTER TABLE "artwork_mockup_renders" DROP CONSTRAINT "FK_1f670ee5397062b364c69a28fa0"`);
        await queryRunner.query(`ALTER TABLE "cod_collections" DROP CONSTRAINT "FK_6e62e27fb72e942cd7c5a71cae9"`);
        await queryRunner.query(`ALTER TABLE "cod_collections" DROP CONSTRAINT "FK_a4b3b775b423b95c084e9cf67ed"`);
        await queryRunner.query(`ALTER TABLE "cod_collections" DROP CONSTRAINT "FK_0795a96c2d82de035ed1f76d505"`);
        await queryRunner.query(`ALTER TABLE "qr_payment_receipts" DROP CONSTRAINT "FK_0586e8f04b0d23e1829ff962bc5"`);
        await queryRunner.query(`ALTER TABLE "qr_payment_receipts" DROP CONSTRAINT "FK_4f1c5984edfa53b368de0ba95ca"`);
        await queryRunner.query(`ALTER TABLE "qr_payment_receipts" DROP CONSTRAINT "FK_5ed72366aea950d412e54fc336e"`);
        await queryRunner.query(`ALTER TABLE "qr_payment_receipts" DROP CONSTRAINT "FK_e1b918f8a3242def69efa2f8ae8"`);
        await queryRunner.query(`ALTER TABLE "qr_payment_receipts" DROP CONSTRAINT "FK_9edbb605ea3d25cff2b6afe9d9a"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP CONSTRAINT "FK_b00d01b12915d8aefab8806cfee"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP CONSTRAINT "FK_bfb05759855bf6da289123ee9cd"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP CONSTRAINT "FK_3dfd4035df06755fed74ed9a667"`);
        await queryRunner.query(`ALTER TABLE "pickup_qa_submissions" DROP CONSTRAINT "FK_68f312df26e22b3090e4e0ce8e2"`);
        await queryRunner.query(`ALTER TABLE "pickup_qa_submissions" DROP CONSTRAINT "FK_329712563e73857f495256914d0"`);
        await queryRunner.query(`ALTER TABLE "service_addons" DROP CONSTRAINT "FK_2f041a59cfc5c4b85b2f04708d4"`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "FK_5f151d414daab0290f65b517ed4"`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" DROP CONSTRAINT "FK_47ad026956606bbc43a0f47ab68"`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" DROP CONSTRAINT "FK_efef9648ccb478a9f43efaa2223"`);
        await queryRunner.query(`ALTER TABLE "rider_profiles" DROP CONSTRAINT "FK_750cddd36444ac18bb47b26de12"`);
        await queryRunner.query(`ALTER TABLE "supplier_profiles" DROP CONSTRAINT "FK_d8f0b495dba71509b24110ef9ea"`);
        await queryRunner.query(`ALTER TABLE "supplier_verifications" DROP CONSTRAINT "FK_ac4469cd2ce4bd70f2c14ea2cbe"`);
        await queryRunner.query(`ALTER TABLE "supplier_verifications" DROP CONSTRAINT "FK_f158ddce866302cc0af9bbc9022"`);
        await queryRunner.query(`ALTER TABLE "supplier_capabilities" DROP CONSTRAINT "FK_2a232dc1548bdf87736c71fa4b3"`);
        await queryRunner.query(`DROP INDEX "public"."idx_conv_status_type"`);
        await queryRunner.query(`CREATE TYPE "public"."chat_messages_sender_role_enum_old" AS ENUM('customer', 'admin', 'rider', 'bot')`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ALTER COLUMN "sender_role" TYPE "public"."chat_messages_sender_role_enum_old" USING "sender_role"::"text"::"public"."chat_messages_sender_role_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."chat_messages_sender_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."chat_messages_sender_role_enum_old" RENAME TO "chat_messages_sender_role_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."chat_conversations_type_enum_old" AS ENUM('ai', 'admin', 'rider')`);
        await queryRunner.query(`ALTER TABLE "chat_conversations" ALTER COLUMN "type" TYPE "public"."chat_conversations_type_enum_old" USING "type"::"text"::"public"."chat_conversations_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."chat_conversations_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."chat_conversations_type_enum_old" RENAME TO "chat_conversations_type_enum"`);
        await queryRunner.query(`CREATE INDEX "idx_conv_status_type" ON "chat_conversations" ("type", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."home_feed_settings_mode_enum_old" AS ENUM('auto', 'community', 'promo')`);
        await queryRunner.query(`ALTER TABLE "home_feed_settings" ALTER COLUMN "mode" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "home_feed_settings" ALTER COLUMN "mode" TYPE "public"."home_feed_settings_mode_enum_old" USING "mode"::"text"::"public"."home_feed_settings_mode_enum_old"`);
        await queryRunner.query(`ALTER TABLE "home_feed_settings" ALTER COLUMN "mode" SET DEFAULT 'auto'`);
        await queryRunner.query(`DROP TYPE "public"."home_feed_settings_mode_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."home_feed_settings_mode_enum_old" RENAME TO "home_feed_settings_mode_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."issues_payout_impact_enum_old" AS ENUM('none', 'hold', 'freeze', 'release')`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "payout_impact" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "payout_impact" TYPE "public"."issues_payout_impact_enum_old" USING "payout_impact"::"text"::"public"."issues_payout_impact_enum_old"`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "payout_impact" SET DEFAULT 'hold'`);
        await queryRunner.query(`DROP TYPE "public"."issues_payout_impact_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."issues_payout_impact_enum_old" RENAME TO "issues_payout_impact_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."issues_status_enum_old" AS ENUM('open', 'under_review', 'resolved_refund', 'resolved_reprint', 'resolved_adjustment', 'rejected', 'closed')`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "status" TYPE "public"."issues_status_enum_old" USING "status"::"text"::"public"."issues_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "status" SET DEFAULT 'open'`);
        await queryRunner.query(`DROP TYPE "public"."issues_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."issues_status_enum_old" RENAME TO "issues_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."supplier_assignments_decision_enum_old" AS ENUM('pending', 'accepted', 'declined', 'expired', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "supplier_assignments" ALTER COLUMN "decision" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "supplier_assignments" ALTER COLUMN "decision" TYPE "public"."supplier_assignments_decision_enum_old" USING "decision"::"text"::"public"."supplier_assignments_decision_enum_old"`);
        await queryRunner.query(`ALTER TABLE "supplier_assignments" ALTER COLUMN "decision" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."supplier_assignments_decision_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."supplier_assignments_decision_enum_old" RENAME TO "supplier_assignments_decision_enum"`);
        await queryRunner.query(`ALTER TABLE "artwork_mockup_renders" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "artwork_mockup_renders" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "artwork_mockup_renders" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "artwork_mockup_renders" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."cod_collections_status_enum_old" AS ENUM('pending', 'collected', 'failed', 'reconciled')`);
        await queryRunner.query(`ALTER TABLE "cod_collections" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "cod_collections" ALTER COLUMN "status" TYPE "public"."cod_collections_status_enum_old" USING "status"::"text"::"public"."cod_collections_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "cod_collections" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."cod_collections_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."cod_collections_status_enum_old" RENAME TO "cod_collections_status_enum"`);
        await queryRunner.query(`ALTER TABLE "qr_payment_receipts" DROP CONSTRAINT "UQ_9edbb605ea3d25cff2b6afe9d9a"`);
        await queryRunner.query(`CREATE TYPE "public"."file_metadata_purpose_enum_old" AS ENUM('general', 'paper', 'proof_of_delivery', 'beta_testimonial', 'legacy', 'payment_receipt')`);
        await queryRunner.query(`ALTER TABLE "file_metadata" ALTER COLUMN "purpose" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "file_metadata" ALTER COLUMN "purpose" TYPE "public"."file_metadata_purpose_enum_old" USING "purpose"::"text"::"public"."file_metadata_purpose_enum_old"`);
        await queryRunner.query(`ALTER TABLE "file_metadata" ALTER COLUMN "purpose" SET DEFAULT 'general'`);
        await queryRunner.query(`DROP TYPE "public"."file_metadata_purpose_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."file_metadata_purpose_enum_old" RENAME TO "file_metadata_purpose_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."payouts_settlement_state_enum_old" AS ENUM('pending', 'held', 'released', 'settled', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "settlement_state" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "settlement_state" TYPE "public"."payouts_settlement_state_enum_old" USING "settlement_state"::"text"::"public"."payouts_settlement_state_enum_old"`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "settlement_state" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."payouts_settlement_state_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payouts_settlement_state_enum_old" RENAME TO "payouts_settlement_state_enum"`);
        await queryRunner.query(`ALTER TABLE "pickup_qa_submissions" ALTER COLUMN "checklist_results" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "product_categories" ALTER COLUMN "allowed_extensions" SET DEFAULT '[]'`);
        await queryRunner.query(`CREATE TYPE "public"."quality_reviews_risk_level_enum_old" AS ENUM('low', 'medium', 'high')`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" ALTER COLUMN "risk_level" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" ALTER COLUMN "risk_level" TYPE "public"."quality_reviews_risk_level_enum_old" USING "risk_level"::"text"::"public"."quality_reviews_risk_level_enum_old"`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" ALTER COLUMN "risk_level" SET DEFAULT 'low'`);
        await queryRunner.query(`DROP TYPE "public"."quality_reviews_risk_level_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."quality_reviews_risk_level_enum_old" RENAME TO "quality_reviews_risk_level_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."quality_reviews_decision_enum_old" AS ENUM('needs_correction', 'proof_approval', 'approved_for_matching', 'blocked')`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" ALTER COLUMN "decision" TYPE "public"."quality_reviews_decision_enum_old" USING "decision"::"text"::"public"."quality_reviews_decision_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."quality_reviews_decision_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."quality_reviews_decision_enum_old" RENAME TO "quality_reviews_decision_enum"`);
        await queryRunner.query(`ALTER TABLE "rider_profiles" ALTER COLUMN "verification_status" SET DEFAULT 'verified'`);
        await queryRunner.query(`CREATE TYPE "public"."orders_payment_authorization_status_enum_old" AS ENUM('none', 'authorized', 'failed', 'expired')`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "payment_authorization_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "payment_authorization_status" TYPE "public"."orders_payment_authorization_status_enum_old" USING "payment_authorization_status"::"text"::"public"."orders_payment_authorization_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "payment_authorization_status" SET DEFAULT 'none'`);
        await queryRunner.query(`DROP TYPE "public"."orders_payment_authorization_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."orders_payment_authorization_status_enum_old" RENAME TO "orders_payment_authorization_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."users_profile_category_enum_old" AS ENUM('student', 'professional', 'supplier')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "profile_category" TYPE "public"."users_profile_category_enum_old" USING "profile_category"::"text"::"public"."users_profile_category_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."users_profile_category_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."users_profile_category_enum_old" RENAME TO "users_profile_category_enum"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_qr_payment_receipts_order_id" ON "qr_payment_receipts" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "idx_product_categories_parent_id" ON "product_categories" ("parent_id") `);
        await queryRunner.query(`CREATE INDEX "idx_users_beta_enrollment_rank" ON "users" ("id", "beta_enrolled_at") WHERE (is_beta_user = true)`);
        await queryRunner.query(`ALTER TABLE "audit_events" ADD CONSTRAINT "FK_audit_events_actor_id" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_events" ADD CONSTRAINT "FK_audit_events_order_id" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_issues_order_id" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_issues_opened_by_user_id" FOREIGN KEY ("opened_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_issues_resolved_by_user_id" FOREIGN KEY ("resolved_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_assignments" ADD CONSTRAINT "FK_supplier_assignments_order_id" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_assignments" ADD CONSTRAINT "FK_supplier_assignments_supplier_id" FOREIGN KEY ("supplier_id") REFERENCES "supplier_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artwork_mockup_renders" ADD CONSTRAINT "FK_mockup_artwork_file" FOREIGN KEY ("artwork_file_id") REFERENCES "file_metadata"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artwork_mockup_renders" ADD CONSTRAINT "FK_mockup_order" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cod_collections" ADD CONSTRAINT "FK_cod_collections_order_id" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cod_collections" ADD CONSTRAINT "FK_cod_collections_rider_id" FOREIGN KEY ("rider_id") REFERENCES "rider_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cod_collections" ADD CONSTRAINT "FK_cod_collections_reconciled_by_user_id" FOREIGN KEY ("reconciled_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qr_payment_receipts" ADD CONSTRAINT "qr_payment_receipts_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qr_payment_receipts" ADD CONSTRAINT "qr_payment_receipts_batch_order_id_fkey" FOREIGN KEY ("batch_order_id") REFERENCES "batch_orders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qr_payment_receipts" ADD CONSTRAINT "qr_payment_receipts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qr_payment_receipts" ADD CONSTRAINT "qr_payment_receipts_file_id_fkey" FOREIGN KEY ("file_id") REFERENCES "file_metadata"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qr_payment_receipts" ADD CONSTRAINT "qr_payment_receipts_verified_by_user_id_fkey" FOREIGN KEY ("verified_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD CONSTRAINT "FK_payouts_supplier_id" FOREIGN KEY ("supplier_id") REFERENCES "supplier_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD CONSTRAINT "FK_payouts_order_id" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD CONSTRAINT "FK_payouts_release_authority_id" FOREIGN KEY ("release_authority_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pickup_qa_submissions" ADD CONSTRAINT "pickup_qa_submissions_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pickup_qa_submissions" ADD CONSTRAINT "pickup_qa_submissions_actor_user_id_fkey" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_addons" ADD CONSTRAINT "FK_service_addons_product_category" FOREIGN KEY ("category_id") REFERENCES "product_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "fk_product_categories_parent" FOREIGN KEY ("parent_id") REFERENCES "product_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" ADD CONSTRAINT "FK_quality_reviews_order_id" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" ADD CONSTRAINT "FK_quality_reviews_reviewer_id" FOREIGN KEY ("reviewer_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_assignments" ADD CONSTRAINT "FK_delivery_assignments_proof_file" FOREIGN KEY ("proof_file_id") REFERENCES "file_metadata"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rider_profiles" ADD CONSTRAINT "FK_rider_profiles_verification_reviewed_by" FOREIGN KEY ("verification_reviewed_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_profiles" ADD CONSTRAINT "FK_supplier_profiles_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_profiles" ADD CONSTRAINT "fk_supplier_profiles_logo_file" FOREIGN KEY ("logo_file_id") REFERENCES "file_metadata"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_verifications" ADD CONSTRAINT "FK_supplier_verifications_supplier_id" FOREIGN KEY ("supplier_id") REFERENCES "supplier_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_verifications" ADD CONSTRAINT "FK_supplier_verifications_reviewed_by" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_capabilities" ADD CONSTRAINT "FK_supplier_capabilities_supplier_id" FOREIGN KEY ("supplier_id") REFERENCES "supplier_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_orders_file_metadata" FOREIGN KEY ("file_metadata_id") REFERENCES "file_metadata"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_order_items_file_metadata" FOREIGN KEY ("file_metadata_id") REFERENCES "file_metadata"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_users_beta_photo_file" FOREIGN KEY ("beta_photo_file_id") REFERENCES "file_metadata"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

}
