import type { DashboardKPIs, ChartDataPoint } from "@/types/dashboard";
import type { Order } from "@/types/order";
import type { DriverProfile } from "@/types/driver";

export const mockKPIs: DashboardKPIs = {
  new_orders_count: 5,
  in_production_count: 3,
  ready_for_pickup_count: 2,
  delivered_count: 128,
  monthly_revenue: 45200,
};

export const mockSalesData: ChartDataPoint[] = [
  { month: "Oct", value: 32000 },
  { month: "Nov", value: 38500 },
  { month: "Dec", value: 41000 },
  { month: "Jan", value: 35200 },
  { month: "Feb", value: 42800 },
  { month: "Mar", value: 45200 },
];

export const mockVolumeData: ChartDataPoint[] = [
  { month: "Oct", value: 85 },
  { month: "Nov", value: 102 },
  { month: "Dec", value: 115 },
  { month: "Jan", value: 94 },
  { month: "Feb", value: 110 },
  { month: "Mar", value: 128 },
];

export const mockOrders: Order[] = [
  {
    id: "1",
    order_id: "ORD-00147",
    user_id: "usr_001",
    category: "paper",
    file_name: "thesis_final.pdf",
    file_url: "https://storage.grid.ph/files/thesis_final.pdf",
    paper_specs: {
      paper_size: "a4",
      color_mode: "full_color",
      media_type: "matte",
      print_sides: "back_to_back",
      binding: "spiral",
    },
    quantity: 3,
    total_price: 450,
    delivery_fee: 50,
    payment_method: "gcash",
    payment_status: "paid",
    order_status: "printing_in_progress",
    delivery_option: "delivery",
    delivery_address_id: "addr_001",
    estimated_completion_at: "2026-03-31T14:00:00Z",
    admin_notes: "Rush order — customer needs by Friday",
    created_at: "2026-03-28T09:15:00Z",
    updated_at: "2026-03-29T11:30:00Z",
  },
  {
    id: "2",
    order_id: "ORD-00148",
    user_id: "usr_002",
    category: "3d",
    file_name: "figurine_v3.stl",
    three_d_specs: {
      file_format: "stl",
      material: "pla",
      color: "White",
      infill_percentage: 20,
      layer_height: 0.2,
      supports: true,
      notes: "Please orient upright",
    },
    quantity: 1,
    total_price: 1200,
    delivery_fee: 0,
    payment_method: "cod",
    payment_status: "pending",
    order_status: "order_placed",
    delivery_option: "pickup",
    created_at: "2026-03-29T15:45:00Z",
    updated_at: "2026-03-29T15:45:00Z",
  },
  {
    id: "3",
    order_id: "ORD-00149",
    user_id: "usr_003",
    category: "paper",
    file_name: "poster_design.pdf",
    paper_specs: {
      paper_size: "a1",
      color_mode: "full_color",
      media_type: "glossy",
      print_sides: "front_only",
      binding: "none",
    },
    quantity: 5,
    total_price: 2500,
    delivery_fee: 80,
    payment_method: "maya",
    payment_status: "paid",
    order_status: "ready_for_dispatch",
    delivery_option: "delivery",
    created_at: "2026-03-27T08:00:00Z",
    updated_at: "2026-03-29T16:00:00Z",
  },
  {
    id: "4",
    order_id: "ORD-00150",
    user_id: "usr_001",
    category: "paper",
    file_name: "flyers_batch.pdf",
    paper_specs: {
      paper_size: "a5",
      color_mode: "full_color",
      media_type: "glossy",
      print_sides: "front_only",
      binding: "none",
    },
    quantity: 100,
    total_price: 3500,
    delivery_fee: 100,
    payment_method: "gcash",
    payment_status: "paid",
    order_status: "delivered",
    delivery_option: "delivery",
    assigned_driver_id: "drv_001",
    created_at: "2026-03-20T10:00:00Z",
    updated_at: "2026-03-25T14:00:00Z",
  },
  {
    id: "5",
    order_id: "ORD-00151",
    user_id: "usr_004",
    category: "paper",
    file_name: "business_cards.pdf",
    paper_specs: {
      paper_size: "custom",
      color_mode: "full_color",
      media_type: "matte",
      print_sides: "back_to_back",
      binding: "none",
    },
    quantity: 200,
    total_price: 1800,
    delivery_fee: 50,
    payment_method: "cod",
    payment_status: "pending",
    order_status: "file_verified",
    delivery_option: "delivery",
    created_at: "2026-03-29T18:00:00Z",
    updated_at: "2026-03-29T18:30:00Z",
  },
];

export const mockDrivers: DriverProfile[] = [
  {
    id: "drv_001",
    user_id: "usr_010",
    full_name: "Juan Reyes",
    vehicle_type: "motorcycle",
    plate_number: "ABC-1234",
    is_available: true,
    created_at: "2026-01-15T00:00:00Z",
    updated_at: "2026-03-29T10:00:00Z",
  },
  {
    id: "drv_002",
    user_id: "usr_011",
    full_name: "Marco dela Cruz",
    vehicle_type: "motorcycle",
    plate_number: "XYZ-5678",
    is_available: true,
    created_at: "2026-02-01T00:00:00Z",
    updated_at: "2026-03-29T09:00:00Z",
  },
  {
    id: "drv_003",
    user_id: "usr_012",
    full_name: "Carlos Santos",
    vehicle_type: "car",
    plate_number: "DEF-9012",
    is_available: false,
    created_at: "2026-02-20T00:00:00Z",
    updated_at: "2026-03-29T08:00:00Z",
  },
];

export const mockStatusHistory = [
  {
    id: "h1",
    order_id: "1",
    from_status: "order_placed",
    to_status: "file_verified",
    changed_by_user_id: "admin_001",
    notes: "File looks good",
    created_at: "2026-03-28T10:00:00Z",
  },
  {
    id: "h2",
    order_id: "1",
    from_status: "file_verified",
    to_status: "printing_in_progress",
    changed_by_user_id: "admin_001",
    created_at: "2026-03-29T11:30:00Z",
  },
];
