import { MigrationInterface, QueryRunner } from "typeorm";

export class AddDeliveryFeePerKm1787227930456 implements MigrationInterface {
    name = 'AddDeliveryFeePerKm1787227930456'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "supplier_profiles" DROP CONSTRAINT "CHK_supplier_profiles_location"`);
        await queryRunner.query(`ALTER TABLE "delivery_settings" ADD "delivery_fee_per_km" numeric(10,2) NOT NULL DEFAULT '50'`);
        await queryRunner.query(`ALTER TYPE "public"."orders_payment_authorization_status_enum" RENAME TO "orders_payment_authorization_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."orders_payment_authorization_status_enum" AS ENUM('none', 'authorized', 'failed', 'expired')`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "payment_authorization_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "payment_authorization_status" TYPE "public"."orders_payment_authorization_status_enum" USING "payment_authorization_status"::"text"::"public"."orders_payment_authorization_status_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "payment_authorization_status" SET DEFAULT 'none'`);
        await queryRunner.query(`DROP TYPE "public"."orders_payment_authorization_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "product_categories" ALTER COLUMN "allowed_extensions" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TYPE "public"."quality_reviews_decision_enum" RENAME TO "quality_reviews_decision_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."quality_reviews_decision_enum" AS ENUM('needs_correction', 'proof_approval', 'approved_for_matching', 'blocked')`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" ALTER COLUMN "decision" TYPE "public"."quality_reviews_decision_enum" USING "decision"::"text"::"public"."quality_reviews_decision_enum"`);
        await queryRunner.query(`DROP TYPE "public"."quality_reviews_decision_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."quality_reviews_risk_level_enum" RENAME TO "quality_reviews_risk_level_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."quality_reviews_risk_level_enum" AS ENUM('low', 'medium', 'high')`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" ALTER COLUMN "risk_level" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" ALTER COLUMN "risk_level" TYPE "public"."quality_reviews_risk_level_enum" USING "risk_level"::"text"::"public"."quality_reviews_risk_level_enum"`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" ALTER COLUMN "risk_level" SET DEFAULT 'low'`);
        await queryRunner.query(`DROP TYPE "public"."quality_reviews_risk_level_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."payouts_settlement_state_enum" RENAME TO "payouts_settlement_state_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."payouts_settlement_state_enum" AS ENUM('pending', 'held', 'released', 'settled', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "settlement_state" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "settlement_state" TYPE "public"."payouts_settlement_state_enum" USING "settlement_state"::"text"::"public"."payouts_settlement_state_enum"`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "settlement_state" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."payouts_settlement_state_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."file_metadata_purpose_enum" RENAME TO "file_metadata_purpose_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."file_metadata_purpose_enum" AS ENUM('general', 'paper', 'proof_of_delivery', 'beta_testimonial', 'payment_receipt', 'legacy')`);
        await queryRunner.query(`ALTER TABLE "file_metadata" ALTER COLUMN "purpose" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "file_metadata" ALTER COLUMN "purpose" TYPE "public"."file_metadata_purpose_enum" USING "purpose"::"text"::"public"."file_metadata_purpose_enum"`);
        await queryRunner.query(`ALTER TABLE "file_metadata" ALTER COLUMN "purpose" SET DEFAULT 'general'`);
        await queryRunner.query(`DROP TYPE "public"."file_metadata_purpose_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."cod_collections_status_enum" RENAME TO "cod_collections_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."cod_collections_status_enum" AS ENUM('pending', 'collected', 'failed', 'reconciled')`);
        await queryRunner.query(`ALTER TABLE "cod_collections" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "cod_collections" ALTER COLUMN "status" TYPE "public"."cod_collections_status_enum" USING "status"::"text"::"public"."cod_collections_status_enum"`);
        await queryRunner.query(`ALTER TABLE "cod_collections" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."cod_collections_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."issues_status_enum" RENAME TO "issues_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."issues_status_enum" AS ENUM('open', 'under_review', 'resolved_refund', 'resolved_reprint', 'resolved_adjustment', 'rejected', 'closed')`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "status" TYPE "public"."issues_status_enum" USING "status"::"text"::"public"."issues_status_enum"`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "status" SET DEFAULT 'open'`);
        await queryRunner.query(`DROP TYPE "public"."issues_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."issues_payout_impact_enum" RENAME TO "issues_payout_impact_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."issues_payout_impact_enum" AS ENUM('none', 'hold', 'freeze', 'release')`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "payout_impact" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "payout_impact" TYPE "public"."issues_payout_impact_enum" USING "payout_impact"::"text"::"public"."issues_payout_impact_enum"`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "payout_impact" SET DEFAULT 'hold'`);
        await queryRunner.query(`DROP TYPE "public"."issues_payout_impact_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."home_feed_settings_mode_enum" RENAME TO "home_feed_settings_mode_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."home_feed_settings_mode_enum" AS ENUM('auto', 'community', 'promo')`);
        await queryRunner.query(`ALTER TABLE "home_feed_settings" ALTER COLUMN "mode" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "home_feed_settings" ALTER COLUMN "mode" TYPE "public"."home_feed_settings_mode_enum" USING "mode"::"text"::"public"."home_feed_settings_mode_enum"`);
        await queryRunner.query(`ALTER TABLE "home_feed_settings" ALTER COLUMN "mode" SET DEFAULT 'auto'`);
        await queryRunner.query(`DROP TYPE "public"."home_feed_settings_mode_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."supplier_assignments_decision_enum" RENAME TO "supplier_assignments_decision_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."supplier_assignments_decision_enum" AS ENUM('pending', 'accepted', 'declined', 'expired', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "supplier_assignments" ALTER COLUMN "decision" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "supplier_assignments" ALTER COLUMN "decision" TYPE "public"."supplier_assignments_decision_enum" USING "decision"::"text"::"public"."supplier_assignments_decision_enum"`);
        await queryRunner.query(`ALTER TABLE "supplier_assignments" ALTER COLUMN "decision" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."supplier_assignments_decision_enum_old"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."supplier_assignments_decision_enum_old" AS ENUM('pending', 'accepted', 'declined', 'expired', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "supplier_assignments" ALTER COLUMN "decision" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "supplier_assignments" ALTER COLUMN "decision" TYPE "public"."supplier_assignments_decision_enum_old" USING "decision"::"text"::"public"."supplier_assignments_decision_enum_old"`);
        await queryRunner.query(`ALTER TABLE "supplier_assignments" ALTER COLUMN "decision" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."supplier_assignments_decision_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."supplier_assignments_decision_enum_old" RENAME TO "supplier_assignments_decision_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."home_feed_settings_mode_enum_old" AS ENUM('auto', 'community', 'promo')`);
        await queryRunner.query(`ALTER TABLE "home_feed_settings" ALTER COLUMN "mode" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "home_feed_settings" ALTER COLUMN "mode" TYPE "public"."home_feed_settings_mode_enum_old" USING "mode"::"text"::"public"."home_feed_settings_mode_enum_old"`);
        await queryRunner.query(`ALTER TABLE "home_feed_settings" ALTER COLUMN "mode" SET DEFAULT 'auto'`);
        await queryRunner.query(`DROP TYPE "public"."home_feed_settings_mode_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."home_feed_settings_mode_enum_old" RENAME TO "home_feed_settings_mode_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."issues_payout_impact_enum_old" AS ENUM('none', 'hold', 'freeze', 'release')`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "payout_impact" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "payout_impact" TYPE "public"."issues_payout_impact_enum_old" USING "payout_impact"::"text"::"public"."issues_payout_impact_enum_old"`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "payout_impact" SET DEFAULT 'hold'`);
        await queryRunner.query(`DROP TYPE "public"."issues_payout_impact_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."issues_payout_impact_enum_old" RENAME TO "issues_payout_impact_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."issues_status_enum_old" AS ENUM('open', 'under_review', 'resolved_refund', 'resolved_reprint', 'resolved_adjustment', 'rejected', 'closed')`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "status" TYPE "public"."issues_status_enum_old" USING "status"::"text"::"public"."issues_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "status" SET DEFAULT 'open'`);
        await queryRunner.query(`DROP TYPE "public"."issues_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."issues_status_enum_old" RENAME TO "issues_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."cod_collections_status_enum_old" AS ENUM('pending', 'collected', 'failed', 'reconciled')`);
        await queryRunner.query(`ALTER TABLE "cod_collections" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "cod_collections" ALTER COLUMN "status" TYPE "public"."cod_collections_status_enum_old" USING "status"::"text"::"public"."cod_collections_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "cod_collections" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."cod_collections_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."cod_collections_status_enum_old" RENAME TO "cod_collections_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."file_metadata_purpose_enum_old" AS ENUM('general', 'paper', 'proof_of_delivery', 'beta_testimonial', 'payment_receipt', 'legacy')`);
        await queryRunner.query(`ALTER TABLE "file_metadata" ALTER COLUMN "purpose" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "file_metadata" ALTER COLUMN "purpose" TYPE "public"."file_metadata_purpose_enum_old" USING "purpose"::"text"::"public"."file_metadata_purpose_enum_old"`);
        await queryRunner.query(`ALTER TABLE "file_metadata" ALTER COLUMN "purpose" SET DEFAULT 'general'`);
        await queryRunner.query(`DROP TYPE "public"."file_metadata_purpose_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."file_metadata_purpose_enum_old" RENAME TO "file_metadata_purpose_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."payouts_settlement_state_enum_old" AS ENUM('pending', 'held', 'released', 'settled', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "settlement_state" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "settlement_state" TYPE "public"."payouts_settlement_state_enum_old" USING "settlement_state"::"text"::"public"."payouts_settlement_state_enum_old"`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "settlement_state" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."payouts_settlement_state_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payouts_settlement_state_enum_old" RENAME TO "payouts_settlement_state_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."quality_reviews_risk_level_enum_old" AS ENUM('low', 'medium', 'high')`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" ALTER COLUMN "risk_level" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" ALTER COLUMN "risk_level" TYPE "public"."quality_reviews_risk_level_enum_old" USING "risk_level"::"text"::"public"."quality_reviews_risk_level_enum_old"`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" ALTER COLUMN "risk_level" SET DEFAULT 'low'`);
        await queryRunner.query(`DROP TYPE "public"."quality_reviews_risk_level_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."quality_reviews_risk_level_enum_old" RENAME TO "quality_reviews_risk_level_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."quality_reviews_decision_enum_old" AS ENUM('needs_correction', 'proof_approval', 'approved_for_matching', 'blocked')`);
        await queryRunner.query(`ALTER TABLE "quality_reviews" ALTER COLUMN "decision" TYPE "public"."quality_reviews_decision_enum_old" USING "decision"::"text"::"public"."quality_reviews_decision_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."quality_reviews_decision_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."quality_reviews_decision_enum_old" RENAME TO "quality_reviews_decision_enum"`);
        await queryRunner.query(`ALTER TABLE "product_categories" ALTER COLUMN "allowed_extensions" SET DEFAULT '[]'`);
        await queryRunner.query(`CREATE TYPE "public"."orders_payment_authorization_status_enum_old" AS ENUM('none', 'authorized', 'failed', 'expired')`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "payment_authorization_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "payment_authorization_status" TYPE "public"."orders_payment_authorization_status_enum_old" USING "payment_authorization_status"::"text"::"public"."orders_payment_authorization_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "payment_authorization_status" SET DEFAULT 'none'`);
        await queryRunner.query(`DROP TYPE "public"."orders_payment_authorization_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."orders_payment_authorization_status_enum_old" RENAME TO "orders_payment_authorization_status_enum"`);
        await queryRunner.query(`ALTER TABLE "delivery_settings" DROP COLUMN "delivery_fee_per_km"`);
        await queryRunner.query(`ALTER TABLE "supplier_profiles" ADD CONSTRAINT "CHK_supplier_profiles_location" CHECK ((((latitude IS NULL) AND (longitude IS NULL)) OR ((latitude IS NOT NULL) AND (longitude IS NOT NULL) AND ((latitude >= ('-90'::integer)::numeric) AND (latitude <= (90)::numeric)) AND ((longitude >= ('-180'::integer)::numeric) AND (longitude <= (180)::numeric)) AND (NOT ((latitude = (0)::numeric) AND (longitude = (0)::numeric))))))`);
    }

}
