import {
  buildAdminUserDetailPayload,
  buildAdminUsersAnalyticsPayload,
  normalizeUserInsightsPeriod,
} from './user-insights';
import { Order, OrderStatus } from '../orders/entities/order.entity';
import { User, UserRole } from '../users/entities/user.entity';

describe('user-insights helpers', () => {
  it('normalizes unsupported periods to 30D', () => {
    expect(normalizeUserInsightsPeriod()).toBe('30D');
    expect(normalizeUserInsightsPeriod('7D')).toBe('7D');
    expect(normalizeUserInsightsPeriod('90D')).toBe('30D');
  });

  it('builds a snake_case admin detail payload with metrics and recent orders', () => {
    const user = {
      id: 11,
      email: 'maria@example.com',
      passwordHash: 'hashed',
      fullName: 'Maria Santos',
      phoneNumber: '+639171234567',
      gender: 'female',
      dateOfBirth: new Date('2001-04-18T00:00:00.000Z'),
      profileCategory: 'student',
      profileField: 'architecture',
      course: 'BS Architecture',
      organization: 'Mapua University',
      printingPreferences: ['plotting_blueprints', 'high_res_color'],
      role: UserRole.CLIENT,
      isProfileComplete: true,
      fcmToken: null,
      isActive: true,
      credits: 0,
      createdAt: new Date('2026-03-01T00:00:00.000Z'),
      updatedAt: new Date('2026-03-15T00:00:00.000Z'),
    } as User;

    const orders = [
      {
        id: 1,
        orderId: 'ORD-001',
        userId: 11,
        category: 'paper',
        fileUrl: 'https://example.com/1.pdf',
        fileName: 'first.pdf',
        quantity: 2,
        totalPrice: 100,
        deliveryFee: 15,
        paymentMethod: 'gcash',
        paymentStatus: 'paid',
        orderStatus: OrderStatus.DELIVERED,
        deliveryOption: 'pickup',
        estimatedCompletionAt: null,
        declineReason: null,
        cancellationReason: null,
        cancelledAt: null,
        deliveryAddressId: null,
        assignedRiderId: null,
        adminNotes: null,
        trackingLink: null,
        createdAt: new Date('2026-03-20T10:00:00.000Z'),
        updatedAt: new Date('2026-03-20T11:00:00.000Z'),
        paperSpec: null,
        threeDSpec: null,
        statusHistory: [],
      },
      {
        id: 2,
        orderId: 'ORD-002',
        userId: 11,
        category: 'paper',
        fileUrl: 'https://example.com/2.pdf',
        fileName: 'second.pdf',
        quantity: 1,
        totalPrice: 250,
        deliveryFee: 0,
        paymentMethod: 'cash',
        paymentStatus: 'pending',
        orderStatus: OrderStatus.SUBMITTED,
        deliveryOption: 'delivery',
        estimatedCompletionAt: null,
        declineReason: null,
        cancellationReason: null,
        cancelledAt: null,
        deliveryAddressId: null,
        assignedRiderId: null,
        adminNotes: null,
        trackingLink: null,
        createdAt: new Date('2026-03-21T10:00:00.000Z'),
        updatedAt: new Date('2026-03-21T11:00:00.000Z'),
        paperSpec: null,
        threeDSpec: null,
        statusHistory: [],
      },
      {
        id: 3,
        orderId: 'ORD-003',
        userId: 99,
        category: 'paper',
        fileUrl: 'https://example.com/3.pdf',
        fileName: 'third.pdf',
        quantity: 1,
        totalPrice: 999,
        deliveryFee: 0,
        paymentMethod: 'cash',
        paymentStatus: 'paid',
        orderStatus: OrderStatus.DELIVERED,
        deliveryOption: 'pickup',
        estimatedCompletionAt: null,
        declineReason: null,
        cancellationReason: null,
        cancelledAt: null,
        deliveryAddressId: null,
        assignedRiderId: null,
        adminNotes: null,
        trackingLink: null,
        createdAt: new Date('2026-03-22T10:00:00.000Z'),
        updatedAt: new Date('2026-03-22T11:00:00.000Z'),
        paperSpec: null,
        threeDSpec: null,
        statusHistory: [],
      },
    ] as Order[];

    const payload = buildAdminUserDetailPayload(user, orders);

    expect(payload).toEqual({
      user: {
        id: 11,
        email: 'maria@example.com',
        full_name: 'Maria Santos',
        phone_number: '+639171234567',
        gender: 'female',
        date_of_birth: new Date('2001-04-18T00:00:00.000Z'),
        profile_category: 'student',
        profile_field: 'architecture',
        course: 'BS Architecture',
        organization: 'Mapua University',
        printing_preferences: ['plotting_blueprints', 'high_res_color'],
        role: UserRole.CLIENT,
        is_active: true,
        is_profile_complete: true,
        created_at: new Date('2026-03-01T00:00:00.000Z'),
        updated_at: new Date('2026-03-15T00:00:00.000Z'),
      },
      metrics: {
        total_orders: 2,
        paid_orders: 1,
        total_spend: 100,
        average_order_value: 100,
        last_order_at: new Date('2026-03-21T10:00:00.000Z'),
        last_paid_order_at: new Date('2026-03-20T10:00:00.000Z'),
      },
      recent_orders: [
        expect.objectContaining({
          order_id: 'ORD-002',
          created_at: new Date('2026-03-21T10:00:00.000Z'),
        }),
        expect.objectContaining({
          order_id: 'ORD-001',
          created_at: new Date('2026-03-20T10:00:00.000Z'),
        }),
      ],
    });
  });

  it('builds customer-focused analytics with the selected period and humanized segment labels', () => {
    const users = [
      {
        id: 1,
        email: 'student@example.com',
        passwordHash: 'hashed',
        fullName: 'Student One',
        phoneNumber: null,
        gender: null,
        dateOfBirth: null,
        profileCategory: 'student',
        profileField: 'architecture',
        course: 'BS Architecture',
        organization: 'University A',
        printingPreferences: ['plotting_blueprints'],
        role: UserRole.CLIENT,
        isProfileComplete: true,
        fcmToken: null,
        isActive: true,
        credits: 0,
        createdAt: new Date('2026-03-02T00:00:00.000Z'),
        updatedAt: new Date('2026-03-02T00:00:00.000Z'),
      },
      {
        id: 2,
        email: 'pro@example.com',
        passwordHash: 'hashed',
        fullName: 'Professional Two',
        phoneNumber: null,
        gender: null,
        dateOfBirth: null,
        profileCategory: 'professional',
        profileField: 'business_corporate',
        course: null,
        organization: 'Company B',
        printingPreferences: ['technical_specs'],
        role: UserRole.CLIENT,
        isProfileComplete: false,
        fcmToken: null,
        isActive: true,
        credits: 0,
        createdAt: new Date('2026-03-20T00:00:00.000Z'),
        updatedAt: new Date('2026-03-20T00:00:00.000Z'),
      },
      {
        id: 3,
        email: 'dormant@example.com',
        passwordHash: 'hashed',
        fullName: 'Dormant Three',
        phoneNumber: null,
        gender: null,
        dateOfBirth: null,
        profileCategory: 'student',
        profileField: 'engineering',
        course: 'BS Engineering',
        organization: 'University C',
        printingPreferences: ['document_printing'],
        role: UserRole.CLIENT,
        isProfileComplete: true,
        fcmToken: null,
        isActive: true,
        credits: 0,
        createdAt: new Date('2026-02-15T00:00:00.000Z'),
        updatedAt: new Date('2026-02-15T00:00:00.000Z'),
      },
      {
        id: 4,
        email: 'rider@example.com',
        passwordHash: 'hashed',
        fullName: 'Rider Four',
        phoneNumber: null,
        gender: null,
        dateOfBirth: null,
        profileCategory: null,
        profileField: null,
        course: null,
        organization: null,
        printingPreferences: null,
        role: UserRole.RIDER,
        isProfileComplete: false,
        fcmToken: null,
        isActive: true,
        credits: 0,
        createdAt: new Date('2026-03-10T00:00:00.000Z'),
        updatedAt: new Date('2026-03-10T00:00:00.000Z'),
      },
      {
        id: 5,
        email: 'future@example.com',
        passwordHash: 'hashed',
        fullName: 'Future Five',
        phoneNumber: null,
        gender: null,
        dateOfBirth: null,
        profileCategory: 'professional',
        profileField: 'architecture',
        course: null,
        organization: 'Future Org',
        printingPreferences: ['marketing_materials'],
        role: UserRole.CLIENT,
        isProfileComplete: true,
        fcmToken: null,
        isActive: true,
        credits: 0,
        createdAt: new Date('2026-04-02T00:00:00.000Z'),
        updatedAt: new Date('2026-04-02T00:00:00.000Z'),
      },
    ] as User[];

    const orders = [
      {
        id: 1,
        orderId: 'ORD-101',
        userId: 1,
        category: 'paper',
        fileUrl: null,
        fileName: null,
        quantity: 1,
        totalPrice: 100,
        deliveryFee: 0,
        paymentMethod: 'gcash',
        paymentStatus: 'paid',
        orderStatus: OrderStatus.DELIVERED,
        deliveryOption: 'pickup',
        estimatedCompletionAt: null,
        declineReason: null,
        cancellationReason: null,
        cancelledAt: null,
        deliveryAddressId: null,
        assignedRiderId: null,
        adminNotes: null,
        trackingLink: null,
        createdAt: new Date('2026-03-30T09:00:00.000Z'),
        updatedAt: new Date('2026-03-30T09:00:00.000Z'),
        paperSpec: null,
        threeDSpec: null,
        statusHistory: [],
      },
      {
        id: 2,
        orderId: 'ORD-102',
        userId: 2,
        category: 'paper',
        fileUrl: null,
        fileName: null,
        quantity: 1,
        totalPrice: 75,
        deliveryFee: 0,
        paymentMethod: 'cash',
        paymentStatus: 'paid',
        orderStatus: OrderStatus.DELIVERED,
        deliveryOption: 'pickup',
        estimatedCompletionAt: null,
        declineReason: null,
        cancellationReason: null,
        cancelledAt: null,
        deliveryAddressId: null,
        assignedRiderId: null,
        adminNotes: null,
        trackingLink: null,
        createdAt: new Date('2026-03-10T09:00:00.000Z'),
        updatedAt: new Date('2026-03-10T09:00:00.000Z'),
        paperSpec: null,
        threeDSpec: null,
        statusHistory: [],
      },
      {
        id: 3,
        orderId: 'ORD-103',
        userId: 4,
        category: 'paper',
        fileUrl: null,
        fileName: null,
        quantity: 1,
        totalPrice: 999,
        deliveryFee: 0,
        paymentMethod: 'cash',
        paymentStatus: 'paid',
        orderStatus: OrderStatus.DELIVERED,
        deliveryOption: 'pickup',
        estimatedCompletionAt: null,
        declineReason: null,
        cancellationReason: null,
        cancelledAt: null,
        deliveryAddressId: null,
        assignedRiderId: null,
        adminNotes: null,
        trackingLink: null,
        createdAt: new Date('2026-03-25T09:00:00.000Z'),
        updatedAt: new Date('2026-03-25T09:00:00.000Z'),
        paperSpec: null,
        threeDSpec: null,
        statusHistory: [],
      },
      {
        id: 4,
        orderId: 'ORD-104',
        userId: 1,
        category: 'paper',
        fileUrl: null,
        fileName: null,
        quantity: 1,
        totalPrice: 50,
        deliveryFee: 0,
        paymentMethod: 'gcash',
        paymentStatus: 'pending',
        orderStatus: OrderStatus.SUBMITTED,
        deliveryOption: 'pickup',
        estimatedCompletionAt: null,
        declineReason: null,
        cancellationReason: null,
        cancelledAt: null,
        deliveryAddressId: null,
        assignedRiderId: null,
        adminNotes: null,
        trackingLink: null,
        createdAt: new Date('2026-02-20T09:00:00.000Z'),
        updatedAt: new Date('2026-02-20T09:00:00.000Z'),
        paperSpec: null,
        threeDSpec: null,
        statusHistory: [],
      },
      {
        id: 5,
        orderId: 'ORD-105',
        userId: 5,
        category: 'paper',
        fileUrl: null,
        fileName: null,
        quantity: 1,
        totalPrice: 500,
        deliveryFee: 0,
        paymentMethod: 'gcash',
        paymentStatus: 'paid',
        orderStatus: OrderStatus.DELIVERED,
        deliveryOption: 'pickup',
        estimatedCompletionAt: null,
        declineReason: null,
        cancellationReason: null,
        cancelledAt: null,
        deliveryAddressId: null,
        assignedRiderId: null,
        adminNotes: null,
        trackingLink: null,
        createdAt: new Date('2026-04-03T09:00:00.000Z'),
        updatedAt: new Date('2026-04-03T09:00:00.000Z'),
        paperSpec: null,
        threeDSpec: null,
        statusHistory: [],
      },
    ] as Order[];

    const payload = buildAdminUsersAnalyticsPayload(
      users,
      orders,
      '30D',
      new Date('2026-03-31T12:00:00.000Z'),
    );

    expect(payload.summary).toEqual({
      total_customers: 4,
      new_customers: 2,
      active_customers: 2,
      dormant_customers: 2,
      profile_completion_rate: 75,
      total_orders: 2,
      paid_orders: 2,
      total_revenue: 175,
      average_order_value: 87.5,
    });

    expect(payload.signup_trend[0]).toEqual({ label: 'Mar 02', value: 1 });
    expect(payload.signup_trend[payload.signup_trend.length - 1]).toEqual({
      label: 'Mar 31',
      value: 0,
    });
    expect(payload.profile_category_mix).toEqual([
      { label: 'Professional', value: 2 },
      { label: 'Student', value: 2 },
    ]);
    expect(payload.profile_field_mix).toEqual([
      { label: 'Architecture', value: 2 },
      { label: 'Business Corporate', value: 1 },
      { label: 'Engineering', value: 1 },
    ]);
    expect(payload.top_segments).toEqual([
      { label: 'Professional / Architecture', value: 1 },
      { label: 'Professional / Business Corporate', value: 1 },
      { label: 'Student / Architecture', value: 1 },
      { label: 'Student / Engineering', value: 1 },
    ]);
    expect(payload.preference_mix).toEqual([
      { label: 'Document Printing', value: 1 },
      { label: 'Marketing Materials', value: 1 },
      { label: 'Plotting Blueprints', value: 1 },
      { label: 'Technical Specs', value: 1 },
    ]);
    expect(payload.activity_split).toEqual([
      { label: 'Active', value: 2 },
      { label: 'Dormant', value: 2 },
    ]);
    expect(payload.revenue_by_segment).toEqual([
      { label: 'Student / Architecture', value: 100 },
      { label: 'Professional / Business Corporate', value: 75 },
    ]);
  });

  it('builds a six-month signup trend using monthly buckets and ignores future dates', () => {
    const users = [
      {
        id: 1,
        email: 'nov@example.com',
        passwordHash: 'hashed',
        fullName: 'Nov User',
        phoneNumber: null,
        gender: null,
        dateOfBirth: null,
        profileCategory: 'student',
        profileField: 'architecture',
        course: 'Course',
        organization: 'Org',
        printingPreferences: ['plotting_blueprints'],
        role: UserRole.CLIENT,
        isProfileComplete: true,
        fcmToken: null,
        isActive: true,
        credits: 0,
        createdAt: new Date('2025-11-15T00:00:00.000Z'),
        updatedAt: new Date('2025-11-15T00:00:00.000Z'),
      },
      {
        id: 2,
        email: 'feb@example.com',
        passwordHash: 'hashed',
        fullName: 'Feb User',
        phoneNumber: null,
        gender: null,
        dateOfBirth: null,
        profileCategory: 'student',
        profileField: 'engineering',
        course: 'Course',
        organization: 'Org',
        printingPreferences: ['document_printing'],
        role: UserRole.CLIENT,
        isProfileComplete: false,
        fcmToken: null,
        isActive: true,
        credits: 0,
        createdAt: new Date('2026-02-10T00:00:00.000Z'),
        updatedAt: new Date('2026-02-10T00:00:00.000Z'),
      },
      {
        id: 3,
        email: 'future@example.com',
        passwordHash: 'hashed',
        fullName: 'Future User',
        phoneNumber: null,
        gender: null,
        dateOfBirth: null,
        profileCategory: 'professional',
        profileField: 'business_corporate',
        course: null,
        organization: 'Org',
        printingPreferences: ['technical_specs'],
        role: UserRole.CLIENT,
        isProfileComplete: true,
        fcmToken: null,
        isActive: true,
        credits: 0,
        createdAt: new Date('2026-04-01T00:00:00.000Z'),
        updatedAt: new Date('2026-04-01T00:00:00.000Z'),
      },
    ] as User[];

    const payload = buildAdminUsersAnalyticsPayload(
      users,
      [],
      '6M',
      new Date('2026-03-31T12:00:00.000Z'),
    );

    expect(payload.signup_trend).toEqual([
      { label: 'Oct', value: 0 },
      { label: 'Nov', value: 1 },
      { label: 'Dec', value: 0 },
      { label: 'Jan', value: 0 },
      { label: 'Feb', value: 1 },
      { label: 'Mar', value: 0 },
    ]);
    expect(payload.summary.new_customers).toBe(2);
  });
});
