/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/smartphone.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/smartphone.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0.012, 7.511, -0.037]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Smartphone_Material_0.geometry} material={materials.Material} position={[-0.089, -0.021, -0.075]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/smartphone.glb')
